spring.datasource.url=jdbc:mysql://192.168.1.55:3306/titan
spring.datasource.username=user_mc
spring.datasource.password=terra#1xbxt#2aviaterra

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true